import Footer from "@/components/footer"
import NavigationBar from "@/components/nav/navigation-bar"
// import { SpeedInsights } from "@vercel/speed-insights/next"
import type { Metadata } from "next"
import { Lexend } from "next/font/google"
import React from "react"
import { Toaster } from "react-hot-toast"
import "./globals.css"

const inter = Lexend({
  subsets: ["latin", "vietnamese"],
  preload: true,
  adjustFontFallback: true,
  fallback: ["Segoe UI", "Tahoma", "Geneva", "Verdana", "sans-serif"],
})

export const metadata: Metadata = {
  title: "Footex",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* <SpeedInsights /> */}
        <NavigationBar />
        <main className="min-h-screen">{children}</main>
        <Toaster
          position="bottom-center"
          toastOptions={{
            duration: 3000,
          }}
        />
        <Footer />
      </body>
    </html>
  )
}
