import NavigationBar from "@/components/nav/navigation-bar";
import "./globals.css";
import type { Metadata } from "next";
import { Readex_Pro } from "next/font/google";
import Footer from "@/components/footer";
import AuthProvider from "./provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Readex_Pro({
  subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Footex",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProvider>
          <NavigationBar />
          <main className="min-h-screen">{children}</main>
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
